
after_context: 3 
before_context: 3
folder: 'tests'
parallel: true
rules:
  "//ClassDef[re:match('.*Var', @name)]":
    name: "B001"
    description: "Classes with 'Var' in name"
    severity: "warning"
    what: "bad practice"
    ignore: false
  ".//Constant[not(ancestor::Assign) and @type='int']":
    name: "R001"
    description: "Constant with int type"
    what: "bad practice"
    severity: "reject"
    ignore: false
  ".//Constant":
    name: "R001"
    description: "Constant with int type"
    what: "bad practice"
    severity: "reject"
    ignore: false