name: Python test workflow

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.7", "3.8", "3.9", "3.10"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v3
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install lxml
        run: |
          sudo apt-get install libxml2-dev libxslt-dev
          sudo apt-get install python3-lxml
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest
          pip install Cython
          if [ -f requirements_dev.txt ]; then pip install -r requirements_dev.txt; fi
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
          python setup.py install
      - name: Test with pytest
        run: |
          pytest -svv tests
